
```{r}
library(ggplot2)
library(showtext)
library(econDV2)
# add google font: Noto Sans TC for chinese characters
sysfonts::font_add_google('Noto Sans TC')
# turn on showing chinese text in graph device
showtext_auto()
# set our graph theme to use the google font and a classic white back ground
theme_set(
  theme(
    text=element_text(family = "Noto Sans TC")
  )+
    theme_classic()
)
# some handy tool to use later through out the class
gg <- list(
  dash = econDV2::ggdash,
  geom = econDV2::ggbrowse,
  aes = econDV2::ggaes
)
```

```{r}
geom_point(
  aes(
    fill=country,
    stroke=country
  ),
  alpha
)
```

```{r}
geom_point()+
  geom_line()
```

```{r}
data.frame(
  contry=c("J", "J", "J", "usa", "usa"),
  threeValues = c(100, 50, 23)
)
```

####

aes:

  .  alpha

```{r}
data.frame(
  country=,
  alpha=c(1, 0.5, 0.5, 1, ...)
)
```

```{r}
geom_point(
  aes(
    alpha=IsOECD
  )
)
```


## example ##
```{r}
data.frame(
  country=c(1, 2, 3, 4),
  isOECD=c(1, 0, 0, 1)
) -> df0

geom_point(aes(alpha=isOECD),
  df0)
```



```{r}
geom_point(alpha=1,  )+
  geom_point(alpha=0.5,  )
```

