```{r}
pltCOVID=Plot()
pltCOVID$ggplot = ggplot(data=COVIDNationalSum)
pltCOVID$geoms = list(
  geom_tile(
    aes(
      x=factor(yearPlusMonth),
      y=`區域_性別`,
      fill=numberColor
      ),
    width=1,
    height=1
    ),
  geom_vline(
    aes(xintercept = x),
    color= "white",
    size= 0.1
    ),
  geom_hline(
    aes(yintercept = y),
    color= "white",
    size= 0.1)
  )

maxMale <- max(COVIDNationalSum$numberColor)
maxFemale <- min(COVIDNationalSum$numberColor)
pltCOVID$scale = scale_fill_gradient2(
  name = "男女人數",
  low = "#00bbcc",#0098a6
  mid = "#d6dff5",#d7ddf4
  high = "#6304C8",
  na.value = "grey",
  breaks=c(maxMale, maxMale, 0, maxFemale, maxFemale),
  labels=c("男", paste("\n最大值:", maxMale),
    "",paste("\n最大值:", maxFemale*(-1)), "女")
  )
#0098a6 #00BBCC
#e5cdfe
#310264 #6304C8
#3260CA #adc0eb #d6dff5
pltCOVID$others = list(
  scale_x_discrete(
    breaks = c(
      202001, 202007,
      202101, 202107,
      202201, 202207),
    labels = c(
      "2020/01", "2020/07",
      "2021/01", "2021/07",
      "2022/01", '2022/07'),
    name = "時間(年/月)"
    )
  )
#options(scipen = 999)

pltCOVID$theme = list(
  theme(
    legend.position = "bottom",
    axis.title.y = element_text(angle = 0)),
  guides(
    fill = guide_colorbar(
      label.position = "bottom",
      title.position = "left",
      title.vjust = 0.8,
      title.hjust = 0.5)
    )
)

pltCOVID$explain = list(
  labs(
    title="台灣境內各地區COVID傳染病人數",
    subtitle="去除性別未定(U﹑X)",
    caption="資料來源：政府資料開放平臺"
  )
)

pltCOVID$make()

```

```{r}
econDV2::ggdash()
```

```{r}
pltCOVID$make()+
  theme(
  plot.title=element_text(size = 10 #input$title
   ),
  plot.subtitle = element_text(size= 10 #input$subtitle
   ),
  plot.caption = element_text(size=10 #input$caption
   )
  )
```

