```{r}
library(stringr)
library(magrittr)
library(openxlsx)
ageDependencyRatio <- readr::read_csv("C:/Users/user/Downloads/ageDependencyRatio.csv")
ageDependencyRatio_old <- readr::read_csv("C:/Users/user/Downloads/ageDependencyRatio_old.csv")
ageDependencyRatio_young <- readr::read_csv("C:/Users/user/Downloads/ageDependencyRatio_young.csv")
countryName <- read.xlsx("C:/Users/user/Downloads/countryName.xlsx", sheet = "Sheet1")
#主要國家扶養比
#https://data.gov.tw/dataset/39500
data20 <- readr::read_csv("https://ws.ndc.gov.tw/001/administrator/10/relfile/0/13729/23eadb48-741f-4656-a19e-c837ee20c326.csv")

View(data20[is.na(data20$扶養比),])

ageDependencyRatio %<>%
  dplyr::filter(`Country Code`%in%c("GBR","USA"))
ageDependencyRatio_old %<>%
  dplyr::filter(`Country Code`%in%c("GBR","USA"))
ageDependencyRatio_young %<>%
  dplyr::filter(`Country Code`%in%c("GBR","USA"))
ageDependencyRatio <- ageDependencyRatio[c(1, 2, 4, 15, 20)]
ageDependencyRatio_old <- ageDependencyRatio_old[c(1, 2, 4, 15, 20)]
ageDependencyRatio_young <- ageDependencyRatio_young[c(1, 2, 4, 15, 20)]
ageDependencyRatio_USUK <- dplyr::bind_rows(
  ageDependencyRatio,
  ageDependencyRatio_young,
  ageDependencyRatio_old)
ageDependencyRatio_USUK |> 
  tidyr::pivot_longer(
    cols = 4:5,
    names_to = "year",
    values_to = "ratio"
  ) |> 
  tidyr::pivot_wider(
    names_from = `Indicator Code`,
    values_from = ratio
  ) |> 
  dplyr::mutate(
    `國家` = ifelse(
      `Country Code`=="USA", "美國", "英國"
      )
  ) -> ageDependencyRatio_USUK
```

```{r}
dataRatio <- data20[-which(data20$`年別`>2030),]
dataRatio <- dataRatio[-c(7, 8)]
dataRatio[which((dataRatio$國別=="美國")&(dataRatio$年別==1970)),c(4:6)] <- round(
  ageDependencyRatio_USUK[3,c(4:6)],2)
dataRatio[which((dataRatio$國別=="美國")&(dataRatio$年別==1975)),c(4:6)] <- round(
  ageDependencyRatio_USUK[4,c(4:6)],2)
dataRatio[which((dataRatio$國別=="英國")&(dataRatio$年別==1970)),c(4:6)] <- round(
  ageDependencyRatio_USUK[1,c(4:6)],2)

dataRatio |> 
  dplyr::filter(
    `年別` == 2020
  ) -> Temp
Temp$類別 <- "中推估"
dataRatio |> 
  dplyr::bind_rows(Temp) |> 
  dplyr::arrange(`國別`, `年別`) |> 
  dplyr::mutate(
    `線類型` = dplyr::case_when(
      `類別` == "實際" ~ "real",
      `類別` == "中推估" ~ "estimate"
    )
  ) -> dataRatio


dataRatio$`國別` |> 
  factor(levels = nlvs) ->dataRatio$`國別`
nlvs <- c("荷蘭", "奧地利", "瑞典", "義大利", "芬蘭",
  "英國","挪威","西班牙","法國", "德國", "美國",
  "韓國", "日本", "中華民國")

dataRatio |> 
  tidyr::pivot_longer(
    cols = 4:6,
    names_to = "比率類型",
    values_to = "ratio"
  ) -> dataRatio_long
# dataRatio_long |> 
#   dplyr::mutate(
#     `線寬` = ifelse(`國別`== "中華民國", "2", "1")
#   ) -> dataRatio_long

# dataRatio_long |> 
#   dplyr::filter(
#     `國別`== "中華民國"
#   ) -> dataRatio_long_tw
# dataRatio_long_tw$線類型[34:42] <- "estimate_tw"
```

```{r}
pltAgeDR=Plot()
pltAgeDR$ggplot = ggplot(data = dataRatio_long)
pltAgeDR$geom = list(
  geom_line(
    aes(
      x = `年別`,
      y = ratio,
      color = `國別`,
      linetype = `線類型`,
    ),
    size = 1.2
  )
  # geom_line(
  #   data = dataRatio_long_tw,
  #   aes(
  #     x = `年別`,
  #     y = ratio,
  #     linetype = `線類型`,
  #   ),
  #   color = "#00000080",
  #   size = 2
  # ),
  # geom_line(
  #   data = dataRatio_long_tw,
  #   aes(
  #     x = `年別`,
  #     y = ratio,
  #     linetype = `線類型`,
  #   ),
  #   color = "#92E6E6",
  #   size = 1.2
  # )
)

pltAgeDR$scale = list(
  scale_color_manual(
    name = "國家",
    limits = c("中華民國", "美國", "日本", "韓國", "德國"),
    values = c("#524C84", "#FFF9AF", "#D65D7A", "#92E6E6",
      "#d9d9d9"),
    na.value = "#d9d9d9",
    label = c("臺灣", "美國", "日本", "韓國", "歐洲\n國家")
    ),
  scale_linetype_manual(
    name = "數據",
    limits = c("real", "estimate"),
    values = c("solid", "11")
  )
  # scale_size_manual(
  #   limits = c("1", "2"),
  #   values = c(1.2, 2)
  # )
)


pltAgeDR$others = list(
  scale_x_continuous(
    name = "",
    expand = c(0, 0),
    breaks = c(seq(1970, 2030, by=5)),
    labels = c("1970", "", "1980", "", "1990", "", "2000",
               "", "2010", "", "2020", "", "2030")
  ),
  scale_y_continuous(
    name = "比例",
    breaks = c(seq(10, 100, by=10)),
    labels = as.character(c(seq(10, 100, by=10)))
  ),
  guides(linetype = "none")
)

pltAgeDR$theme = list(
  theme(
    panel.grid.major.y = element_line(color="grey", size= 0.1),
    axis.title.y = element_text(angle = 0),
    axis.title.x = element_text(hjust = 1)
    )
)

pltAgeDR$explain = list(
  labs(
    title = "未來青壯年是否會擔起愈多責任？",
    subtitle = "註1: 虛線(2020年後)為中推估的估計資料(假設總生育率維持當前水準)\n註2: 扶養比 = 扶老比 + 扶幼比",
    caption = "資料來源：政府資料開放平臺\n   https://data.gov.tw/dataset/39500"
  )
)

pltAgeDR$make()+
  facet_wrap(
    vars(`比率類型`),
    strip.position = "top",
    )+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(size = 12),
    panel.spacing.x = unit(1, "cm"),
    plot.title = element_text(size = 20 #input$title
    ),
    plot.subtitle = element_text(size= 10 #input$subtitle
    ),
    plot.caption = element_text(size=10 #input$caption
    )
  )
#econDV2::ggdash()
```

```{r}
econDV2::ggdash()
```

