```{r}
if(!require(showtext)) install.packages("showtext")
showtext::showtext_auto()
library(ggplot2)
# set our graph theme to use the google font and a classic white back ground
theme_set(
  theme(
    text=element_text(family = "Noto Sans TC")
  )+
    theme_classic()
)
```

```{r}
googledrive::drive_deauth()
googledrive::drive_download(
  file=googledrive::as_id("https://drive.google.com/file/d/1K8IWyy7G9LAKewjVXMGD8kUbbvjGoRT7/view?usp=sharing"),
  overwrite = T
)

library(readr)
marriage <- read_csv("marriage.csv")
head(marriage)
View(marriage)
```

```{r}
library(dplyr)
marriageTaoYuan = {
  marriage |>
    dplyr::filter(
      # 只看桃園市
      stringr::str_detect(site_id,"桃園市")
    ) -> marriageTaoYuan
  marriageTaoYuan |>
    # 創造行政區欄位
    mutate(
      site_id2 = stringr::str_sub(site_id,4,6)
    ) -> marriageTaoYuan
  
}
```

```{r}
# 結婚年齡
# X：以妻年齡來看
# Y：對數
library(ggplot2)
plt = new.env()
plt$ggplot = ggplot(data=marriageTaoYuan)
plt$geoms = list(
  geom_col(
    mapping=aes(
      x=female_age_or_spouse1,
      y=marry_pair
    ),
    position="stack" # sum across sites within same age group.
  )
)
plt$ggplot + plt$geoms
```

# theme
資料幾何以外的調整
```{r}
plt$ggplot + plt$geoms +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1 #詞的水平座標調整
    )
  )
```

```{r}
marriageTaoYuan |>
  purrr::map(class)

marriageTaoYuan |>
  mutate(
    marry_pair = as.integer(marry_pair)
  ) -> marriageTaoYuan
```



```{r}
plt$ggplot = ggplot(data =  marriageTaoYuan)
plt$geoms = list(
  geom_col(
    mapping=aes(
      x=female_age_or_spouse1,
      y=marry_pair
    ),
    position="stack" # sum across sites within same age group.
  )
)
plt$theme = theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1 #詞的水平座標調整
    )
  )


plt$ggplot + plt$geoms + plt$theme
```

```{r}
marriageTaoYuan$female_age_or_spouse1 |>
  factor() |> 
  levels() -> defaultLevels
lastIndex = length(defaultLevels)

c(
  defaultLevels[[lastIndex]],
  defaultLevels[-lastIndex]
) -> correctLevels

marriageTaoYuan$female_age_or_spouse1 |>
  factor(
    levels = correctLevels
    ) -> marriageTaoYuan$female_age_or_spouse1
```

```{r}
plt$ggplot = ggplot(data =  marriageTaoYuan)
plt$geoms = list(
  geom_col(
    mapping=aes(
      x=female_age_or_spouse1,
      y=marry_pair
    ),
    position="stack" 
    # sum across sites within same age group.
  )
)
plt$theme = theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1 #詞的水平座標調整
    )
  )


plt$ggplot + plt$geoms + plt$theme
```

```{r}
.d = marriageTaoYuan
.d$female_age_or_spouse1 |> 
  unique() -> xx

xx |> 
  stringr::str_extract("[0-9]+") |> 
  as.integer()
```

```{r}
marriageTaoYuan$female_age_or_spouse1 |> 
  factor() |> 
  levels()

allLevels = levels(marriageTaoYuan$female_age_or_spouse1)
lateMarriageLevels = allLevels[-c(1:16)]

marriageTaoYuan$marry_pair |> 
  as.integer() -> marriageTaoYuan$marry_pair

marriageTaoYuan |> 
  dplyr::filter(
    .d$female_age_or_spouse1 %in%
      lateMarriageLevels
    ) |> 
  group_by(site_id2) |> 
  
  summarise(
    late_marry_pair = sum(marry_pair)
  ) -> marriageTaoYuanLate


marriageTaoYuan |> 
  group_by(site_id2) |> 
  summarise(
    total_marry_pair = sum(marry_pair)
  ) -> marriageTaoYuanTotal

marriageTaoYuanLate |> 
  left_join(marriageTaoYuanTotal,
    by=c("site_id2")) -> marriageTaoYuanLate

marriageTaoYuanLate |> 
  mutate(
    prop_marry_pair_late = late_marry_pair / total_marry_pair
  ) -> marriageTaoYuanLate
```

```{r}
ggplot(data=marriageTaoYuanLate)+
geom_col(
  mapping=aes(
    x=site_id2,
    y=prop_marry_pair_late
  )
) + coord_flip() #翻轉成水平長條
```

